name = "SpatialHashing"
uuid = "e2e8a281-5b48-4fd6-b542-65e07fde0794"
authors = ["Alexander Barth <barth.alexander@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
